import Header from "@/components/Header";

const REPO = "https://github.com/jaehong-c/dc-risk";

const SECTIONS = [
  {
    h: "What this is",
    p: [
      "DC Risk Register is a lifecycle risk register and leadership dashboard for data center development projects. You describe a project in about twenty fields (state, capacity, phase, power status, cooling, contract structure, financing, insurance and compliance programs) and the register evaluates 72 curated risks against that profile, scores each on a 5 by 5 likelihood and impact matrix, and produces a one-page memo for leadership.",
      "It was built as a working prototype of how a risk function at a data center developer could keep a register current across site selection, permitting, procurement, construction, commissioning, and operations, rather than as a static spreadsheet refreshed quarterly.",
    ],
  },
  {
    h: "How scoring works",
    p: [
      "Every score is rule-based and reproducible. Each risk carries a base likelihood and base impact (1 to 5) set by the author. Trigger rules then adjust those values from the project profile. A risk about long-lead electrical equipment, for example, gains likelihood when no purchase orders are placed and when fewer than 24 months remain to COD, and loses likelihood once orders are confirmed. Score is likelihood times impact, from 1 to 25. Bands are Low (1 to 4), Medium (5 to 9), High (10 to 15), and Critical (16 to 25).",
      "The structure follows ISO 31000: identification (which risks apply to this phase and configuration), analysis (trigger rules), evaluation (bands and ranking), and treatment (mitigations and key risk indicators carried on each row). The heat matrix follows the COSO-style presentation most boards expect.",
      "Risks are also classified against the project's current phase. Risks whose lifecycle window has not opened are marked upcoming; risks whose window has closed are retired. Only active risks feed the summary, the matrix, and the memo.",
    ],
  },
  {
    h: "Unknown inputs",
    p: [
      "Any input can be set to Unknown. When a trigger depends on an unknown field, it does not fire and the risk is flagged as unverified. The register shows which inputs are missing and which risk scores depend on them, and the memo lists what must be confirmed. The intent is to keep a blank from being read as a favorable answer, which is one of the most common ways registers quietly understate exposure.",
    ],
  },
  {
    h: "Leadership memo",
    p: [
      "The memo is generated by an AI model from the scored register. The model does not score, rank, or add risks; it interprets the deterministic output, connects risks that compound each other, and recommends where attention goes in the next 90 days. Every number in the memo traces back to the register.",
    ],
  },
  {
    h: "Data and limitations",
    p: [
      "The risk library, base scores, and trigger rules were curated by the author from public industry sources and professional judgment. State-level hazard, grid constraint, labor, and policy ratings are ordinal estimates (0 to 3) informed by sources such as the FEMA National Risk Index, NOAA climate summaries, and ISO and RTO reporting. They are not measured values and are not drawn from any company's proprietary data.",
      "This is a prototype. For production use, base scores should be calibrated against a portfolio's actual incident history, state ratings should be replaced with county-level sourced data, and the register should be persisted and versioned so that changes over time are auditable.",
    ],
  },
  {
    h: "Roadmap",
    p: [
      "Planned for the next version: county-level hazard data from the FEMA National Risk Index replacing state ordinals; site geocoding and a map layer; editable scores with an audit trail so a risk owner can override a rule-based value with a documented rationale; saved registers with month-over-month change tracking; and a PDF export of the memo and matrix.",
    ],
  },
  {
    h: "Stack",
    p: [
      "Next.js (App Router, JavaScript), static JSON data layer, rule engine in plain JavaScript, Anthropic API for memo generation behind a server route, deployed on Vercel from GitHub. The full risk library and scoring logic are open in the repository.",
    ],
  },
];

export default function About() {
  return (
    <main className="min-h-screen">
      <Header />
      <div className="mx-auto max-w-[1440px] px-6 py-6">
        <div className="panel" style={{ maxWidth: 820, padding: "36px 40px" }}>
          <p className="eyebrow mb-2">About</p>
          <h1 className="display text-[28px]">
            A lifecycle risk register for data center development
          </h1>
          <p className="mt-3 text-[14px] text-ink-2">
            Built by Jae Chung as a portfolio prototype. Code and data are public on{" "}
            <a href={REPO} target="_blank" rel="noreferrer" className="underline text-ink">GitHub</a>.
          </p>

          {SECTIONS.map((s) => (
            <section key={s.h} className="mt-8">
              <p className="eyebrow mb-2">{s.h}</p>
              {s.p.map((t, i) => (
                <p key={i} className="mb-3 text-[14px] leading-relaxed text-ink-2">
                  {t}
                </p>
              ))}
            </section>
          ))}
        </div>
      </div>
      <footer className="mx-auto max-w-[1440px] px-6 pb-8 pt-2 text-[11px] text-ink-3">
        <p>© 2026 Jae Chung. All rights reserved.</p>
      </footer>
    </main>
  );
}