export const EMPTY_PROFILE = {
    name: "",
    state: "TX",
    capacityMW: 100,
    phase: "permitting",
    targetCOD: "",
    contractType: "gmp",
    gcStatus: "not_selected",
    powerStatus: "in_negotiation",
    powerSource: "grid",
    longLeadStatus: "not_ordered",
    permittingStatus: "in_progress",
    landStatus: "under_contract",
    taxIncentive: "in_negotiation",
    coolingType: "hybrid",
    waterSource: "municipal",
    workloadType: "ai_training",
    tenantStatus: "loi",
    redundancy: "n_plus_1",
    financing: "undecided",
    insuranceStatus: "not_started",
    complianceStatus: "not_started",
    bcdrStatus: "none",
  };
  
  export const PRESETS = [
    {
      label: "West Texas AI campus, early stage",
      profile: {
        ...EMPTY_PROFILE,
        name: "Permian Ridge Campus",
        state: "TX",
        capacityMW: 500,
        phase: "permitting",
        targetCOD: "2028-06-01",
        contractType: "cost_plus",
        gcStatus: "not_selected",
        powerStatus: "in_negotiation",
        powerSource: "hybrid",
        longLeadStatus: "not_ordered",
        permittingStatus: "in_progress",
        landStatus: "option",
        taxIncentive: "in_negotiation",
        coolingType: "liquid",
        waterSource: "groundwater",
        workloadType: "ai_training",
        tenantStatus: "loi",
        redundancy: "n_plus_1",
        financing: "project_finance",
        insuranceStatus: "not_started",
        complianceStatus: "not_started",
        bcdrStatus: "none",
      },
    },
    {
      label: "Northern Virginia hyperscale, under construction",
      profile: {
        ...EMPTY_PROFILE,
        name: "Loudoun Building 3",
        state: "VA",
        capacityMW: 96,
        phase: "construction",
        targetCOD: "2027-03-01",
        contractType: "gmp",
        gcStatus: "selected_dc_experienced",
        powerStatus: "utility_agreement",
        powerSource: "grid",
        longLeadStatus: "partially_ordered",
        permittingStatus: "complete",
        landStatus: "owned",
        taxIncentive: "executed",
        coolingType: "hybrid",
        waterSource: "municipal",
        workloadType: "inference",
        tenantStatus: "signed_hyperscale",
        redundancy: "2n",
        financing: "construction_loan",
        insuranceStatus: "placed",
        complianceStatus: "in_progress",
        bcdrStatus: "drafted",
      },
    },
    {
      label: "Ohio colocation, operating",
      profile: {
        ...EMPTY_PROFILE,
        name: "Columbus Colo Phase 1",
        state: "OH",
        capacityMW: 36,
        phase: "operations",
        targetCOD: "2025-09-01",
        contractType: "gmp",
        gcStatus: "selected_dc_experienced",
        powerStatus: "secured",
        powerSource: "grid",
        longLeadStatus: "ordered",
        permittingStatus: "complete",
        landStatus: "owned",
        taxIncentive: "executed",
        coolingType: "air",
        waterSource: "none",
        workloadType: "colo",
        tenantStatus: "signed_colo",
        redundancy: "n_plus_1",
        financing: "equity",
        insuranceStatus: "placed",
        complianceStatus: "certified",
        bcdrStatus: "tested",
      },
    },
  ];
  
  // Option lists for the form, in display order
  export const OPTIONS = {
    phase: [
      ["site_selection", "Site selection"],
      ["permitting", "Permitting"],
      ["procurement", "Procurement"],
      ["construction", "Construction"],
      ["commissioning", "Commissioning"],
      ["operations", "Operations"],
    ],
    contractType: [
      ["gmp", "GMP"],
      ["lump_sum", "Lump sum"],
      ["cost_plus", "Cost plus"],
      ["design_build", "Design-build"],
    ],
    gcStatus: [
      ["not_selected", "Not selected"],
      ["selected_general", "Selected, general"],
      ["selected_dc_experienced", "Selected, DC experienced"],
    ],
    powerStatus: [
      ["unsecured", "Unsecured"],
      ["in_negotiation", "In negotiation"],
      ["utility_agreement", "Utility agreement"],
      ["secured", "Secured (ESA / PPA)"],
    ],
    powerSource: [
      ["grid", "Grid"],
      ["onsite_gas", "Onsite gas"],
      ["hybrid", "Hybrid"],
    ],
    longLeadStatus: [
      ["not_ordered", "Not ordered"],
      ["partially_ordered", "Partially ordered"],
      ["ordered", "Ordered"],
    ],
    permittingStatus: [
      ["not_started", "Not started"],
      ["in_progress", "In progress"],
      ["complete", "Complete"],
    ],
    landStatus: [
      ["not_secured", "Not secured"],
      ["option", "Option"],
      ["under_contract", "Under contract"],
      ["owned", "Owned"],
    ],
    taxIncentive: [
      ["none", "None"],
      ["in_negotiation", "In negotiation"],
      ["executed", "Executed"],
    ],
    coolingType: [
      ["air", "Air"],
      ["hybrid", "Hybrid"],
      ["liquid", "Liquid"],
    ],
    waterSource: [
      ["none", "None (closed loop)"],
      ["municipal", "Municipal"],
      ["groundwater", "Groundwater"],
      ["reclaimed", "Reclaimed"],
    ],
    workloadType: [
      ["ai_training", "AI training"],
      ["inference", "Inference"],
      ["hpc", "HPC"],
      ["colo", "Colocation"],
    ],
    tenantStatus: [
      ["speculative", "Speculative"],
      ["loi", "LOI"],
      ["signed_colo", "Signed, colo"],
      ["signed_hyperscale", "Signed, hyperscale"],
    ],
    redundancy: [
      ["n", "N"],
      ["n_plus_1", "N+1"],
      ["2n", "2N"],
    ],
    financing: [
      ["undecided", "Undecided"],
      ["equity", "Equity / balance sheet"],
      ["construction_loan", "Construction loan"],
      ["project_finance", "Project finance"],
    ],
    insuranceStatus: [
      ["not_started", "Not started"],
      ["in_progress", "In progress"],
      ["placed", "Placed"],
    ],
    complianceStatus: [
      ["not_started", "Not started"],
      ["in_progress", "In progress"],
      ["certified", "Certified"],
    ],
    bcdrStatus: [
      ["none", "None"],
      ["drafted", "Drafted"],
      ["tested", "Tested"],
    ],
  };